steps:
  # Login to Docker Hub with inline credentials (temporary workaround)
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'echo "dckr_pat_rCJwMMv_qC3DQbmnZ8CjDBPG4BE" | docker login --username=sudhar1 --password-stdin']

  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'sudhar1/omniparser-api:latest',
      '.'
    ]
    dir: '.'

  # Push to Docker Hub
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'sudhar1/omniparser-api:latest']

# Use high-CPU machine for faster builds
options:
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: 100
  logging: CLOUD_LOGGING_ONLY

# Timeout for large ML builds
timeout: 3600s 