steps:
  # Login to Docker Hub
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'echo "$$DOCKER_PASSWORD" | docker login --username=$$DOCKER_USERNAME --password-stdin']
    secretEnv: ['DOCKER_USERNAME', 'DOCKER_PASSWORD']

  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'sudhar1/omniparser-api:latest',
      '.'
    ]
    dir: '.'

  # Push to Docker Hub
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'sudhar1/omniparser-api:latest']

# Configure secrets for Docker Hub authentication
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/docker-hub-username/versions/latest
      env: 'DOCKER_USERNAME'
    - versionName: projects/$PROJECT_ID/secrets/docker-hub-password/versions/latest
      env: 'DOCKER_PASSWORD'

# Use high-CPU machine for faster builds
options:
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: 100
  logging: CLOUD_LOGGING_ONLY

# Timeout for large ML builds
timeout: 3600s 