services:
  omniparser:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 7860:7860
    ipc: host
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
      - ~/.paddleocr:/root/.paddleocr
      - ~/.EasyOCR/:/root/.EasyOCR
    environment:
      - HUGGING_FACE_HUB_TOKEN=${HUGGING_FACE_HUB_TOKEN}
